apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:qSx0afnvC6C2x6PPGYKfB7GB+GjhePwZYW7H472GpIVHXx2/gBaXlQ==,iv:dWb5jy3PwGSlnCKul+MyLpABbgfvrDBQLXJcejAsNIY=,tag:Y2cs02uAnyelUHNDC+EW5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mdljdkg84ln85m4e9vdau4qf6dvrwc39mh2964pxpyyq4aryzgpqua4f04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZTR4dDVRQlFtRXMwTXdW
            bzNHY2J5eE5VZnU4d0RXbUtiMkxXYUdBZndJCmtrbU52c3grY2wwOEI0bSs1L1Rj
            QkphdTVEQ2l4cjJENTBrNTBSWTVuNk0KLS0tIGxldzkveTBFY3N0bDBQWEFtS25r
            VXkyOFJYN2d2U0t0d05scmNWOWsyVU0KjkckZeA5HzyUsBYO89Dy2Z66e8PXhz9g
            XrFZPM7Q6P2tkpbM4dj7TmuopaX0Pl3tMesdA95AHjQNbpk0XVJv+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T20:08:54Z"
    mac: ENC[AES256_GCM,data:cKw7Qkep0XTbKyMdLhynMqmlVZYMji5v2snh3d39tkEJ67OGqNJpmLeN72dxWaXhVJDALhhSRamM/Yj04l+S0QBEzsFIu/tUT6VXuRvy6gbMq3Y4wCtbSPaZildm8XiX/A73YEAtWVqnKMmCJOx7vlb25PPUTNktkS+YUepaZAE=,iv:qgG65a7lQuzB+12YUdAMat2aWV9ax/Yuh9PD3gnc9GY=,tag:z+8HTJr6HauSPGW8/BlH1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
