apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:MWdLPbhHPlEE6OlyvnCr6XxrSPkewM4Qkum+AUi0qAlqzq8/WfPWcw6gab2/zGKjm682aUM/hNmV8/RA7r0DdP+TpG8A8Qm/mcva3L//mmTTPgTJLRZFErzjUqNXpA==,iv:QsbK1AbNqmSQ0f1v27MDJjcT3PuzW9aZJ2UMHayZAmI=,tag:SKyQIeNoWj1Zwx6R0Nr09g==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:ZFRTnUSHVevlO0R3cRL4vI+Qdw==,iv:RmD4ik7w22FkzIP14n1hotpf59S/xW7Xl+mYgPTWiHI=,tag:KQvksV3PWHwXwLxvm7Wlog==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:MQaaC3yqSmac5WuE+z4ADFTs1zT7vfSx,iv:CAAe2Co4bPQ+Dz+vJxAhuPRb6P0QV67aTd8elRpskh8=,tag:QYJ7FkSOtNpisfl+PIVbAg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Y8Ms7kq1tQtsKjmVSATMMaxNY86xSV+cr5NhwQoXY7AZdJqN,iv:2oAaSUfpnuh8JfGjuD8Inxp1PsrqNDThvBpwqzBFv9s=,tag:/aLlGSF4Rpz4PB4ErOF19Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1mdljdkg84ln85m4e9vdau4qf6dvrwc39mh2964pxpyyq4aryzgpqua4f04
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bkwwdHJkZlc3QXoyOFR0
            bVhhbDY5LzU2NzVTR1BLRzBIOTg4NHZ3bFgwCkFXdjBocUgxeVN3bFVFdzFWTDVh
            UzZkVmJQay9zWUdSZmppQmJzYlVCeUUKLS0tIDd5LzlZa1pnKzc1MjNSZFhvb3ZK
            THV6czRIOC81aldYSU1QL1FoMVNuUWMKJ7Ct6rPxR5aD8TVa9rUj9l4pLw74Bqxn
            7Bw7zMlmN3NNiMok8T5VdjFk19tV1OCkyOMRN80ZZV3XwYSHZVtg7Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-05T20:08:54Z"
    mac: ENC[AES256_GCM,data:OIeugJK9XxBL/Q/8TncdO4QDF9UOpsbdcz+8E4QYhoZhseatgzMe/p4PU3E0/SfuK9OjquoR6YMbp7NA11nbYt9Sne672Hl0PhpLYwhoQUD4Wty7VLU36YN/++eoluYSjjY6k4kRXRBWZ2XVI8fb7TMETdjjCqNq24335+G3VQI=,iv:+qFpX4eo5bTuxlNeHTqOohUonJgmGJc80K7oO/pXH4o=,tag:qB4nX8pbndpMv6dOTzkJsw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
